---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: dotnet-helloworld-github
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: dotnet-helloworld-github
    apps.tanzu.vmware.com/has-tests: "false"
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.flavours: steeltoe
    tanzu.app.live.view.application.name: dotnet-helloworld-github
    tanzu.app.live.view.application.actuator.port: "9090"
spec:
  build:
    env:
    - name: DOTNET_CLI_TELEMETRY_OPTOUT
      value: "true"
    - name: BP_DOTNET_PROJECT_PATH
      value: "Server"
    - name: BP_DOTNET_PUBLISH_FLAGS
      value: "--self-contained=true"
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  env:
  - name: DOTNET_CLI_TELEMETRY_OPTOUT
    value: "true"

  source:
    git:
      url: https://github.com/pksheldon4/DotNet-HelloWorld.git
      ref:
        branch: main